apiVersion: apps/v1
kind: Deployment
metadata:
  name: graal-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graal-demo
  template:
    metadata:
      labels:
        app: graal-demo
    spec:
      containers:
      - name: graal-demo
        image: XXX/graal-demo:1.0
        args: ["--spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/demo"]
        ports:
          - containerPort: 8888
        imagePullPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: graal-demo
  namespace: default
spec:
  selector:
    app: graal-demo
  ports:
    - port: 8888
      targetPort: 8888
  type: LoadBalancer