server:
  port: 8888

spring:
  datasource:
    #url: jdbc:postgresql://host.docker.internal:5432/demo
    url: jdbc:postgresql://localhost:5432/demo
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none